name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: build
        run: |
          npm ci
          export NODE_ENV=dev
          npm run build
