name: docs

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          git config --global user.email "talhayut.dev@gmail.com"
          git config --global user.name "Tal Hayut"
          npm ci
          node create.js
          npm run deploy
