name: docs

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: build
        run: |
          git config user.email "talhayut.dev@gmail.com"
          git config user.name "Tal Hayut"
          npm ci
          node create.js
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
